### ISSUE TITLE
Refer to 'whole work'?

### ISSUE THREAD

**Issue by andredelft** [andredelft/heidegger-index#14]
Hebben we een manier nodig om aan te geven dat het lemma het hele werk omvat? Zoiets als `φύσις` bij `WBPh` of `dürftiger Zeit` bij `WD`?

Ik ondervind dat ik vaak dan iets doe als `237ff` (beginpagina, plus rest), maar dat voelt niet helemaal juist (misschien moeten we uberhaupt van die `ff` suffix af: het is eigenlijk te vaag). Alternatief is beginpagina tot en met eindpagina opgeven, maar dat is dan weer zoveel opzoekwerk elke keer. Zou mooi zijn als we een soort shorthand hebben om aan te geven dat de referentie over het hele werk gaat. Bijv. een flag:

```yaml
φύσις:
  references
    WBPh:
    - whole: true
```

**Comment by johannesdewit** [comment]
Het lijkt me inderdaad wel nuttig om in één oogopslag te kunnen zien dat het een lemma een geheel werk omvat. Jouw oplossing bevalt me wel, maar opent wel de deur voor eventuele dubbele referenties naar hetzelfde werk.

Taken:
- [x] `add-ref` aanpassen om 'whole' als een pageref toe te staan.
- [x] Controleer of `whole: true` al bestaat voor het toevoegen.
- [ ] `Lemma` model aanpassen.
- [x] Validatieschema aanpassen.
- [ ] README aanpassen en 'whole' als mogelijke pageref aangeven.
