### ISSUE TITLE
Geen referenties voor werken in de bibliografie

### ISSUE THREAD

**Issue by johannesdewit** [andredelft/heidegger-index#22]
## Symptomen:

Sinds gisteren (werking was nog okee om 18:00) is het volgende probleem op gekomen:
- Geen referenties op ‘work’ pagina's.
- Geen bibliografie.
- De ‘work’-afkortingen onder de lemma's zijn geen links meer (‘_Reference not yet added_’).

## Waarschijnlijke oorzaak:

Blijkbaar worden de referenties niet meer gegenereerd.

## Diagnose:

Als ik lokaal het `populate-index` uitvoer krijg ik de volgende error te zien:
```
Skipping *WORK* reference generation because of HTTP error: 502 Server Error: Bad Gateway for url: https://labs.brill.com/citeproc?style=mhra&responseformat=html
```

Omdat het dus gaat om een onderdeel van de deploy-cyclus is het niet eenvoudig om even naar een vorige versie te gaan.

**Comment by andredelft** [comment]
Ik lees dit nu pas, maar mooie analyse! De oorzaak ligt bij het citeproc endpoint, we leunden nog altijd op die van Brill (https://labs.brill.com/citeproc), die is klaarblijkelijk offline gehaald!

Ik ga binnenkort maar eens mijn eigen hosten, misschien dit weekend even naar kijken.

**Comment by andredelft** [comment]
Opgelost, ik heb mijn eigen server opgezet: https://citeproc.delve.nu.
