### ISSUE TITLE
Tekst niet van Perseus geladen

### ISSUE THREAD

**Issue by johannesdewit** [andredelft/heidegger-index#23]
Voor de volgende lemmata geldt dat de work tekst niet van Perseus wordt geladen:

- Fragment VII (Parmenides)
- Fragment 29 (Heraklit)

Dit gebeurt terwijl de tekst wel beschikbaar is op Perseus, de URN's wel gegeven zijn.

Lokaal laadt hij voor alle lemmata de `perseus_content` als een cts_urn gegeven is tot en met de `passage`, behalve voor deze twee.

**Comment by johannesdewit** [comment]
Lokaal heb ik een oplossing gevonden. Maar als ik hem push, blijft de index leeg. Ik heb hem dus teruggedraaid.

**Comment by johannesdewit** [comment]
> Lokaal heb ik een oplossing gevonden. Maar als ik hem push, blijft de index leeg. Ik heb hem dus teruggedraaid.

Dit gebeurt dus nog steeds. Ik snap alleen niet waarom.

**Comment by andredelft** [comment]
Ik ga er vanuit dat dit probleem verholpen is met #45. Fragment 29 van Heraclitus is in ieder geval gevuld, fragment 7 van Parmenides staat niet (meer?) in onze index, maar alle andere fragmenten van Parmenides staan erin (met overigens nog wat commentaartekst ertussen..)
