### ISSUE TITLE
Holzwege beschrijving wordt niet weergegeven.

### ISSUE THREAD

**Issue by johannesdewit** [andredelft/heidegger-index#31]

**Comment by andredelft** [comment]
De lemma 'Holzwege'? Ik zie daar geen description voor staan in de descriptions folder?

**Comment by johannesdewit** [comment]
Ik had hem veranderd naar `ga-5.md` om te kijken of dat wel werkte.

**Comment by andredelft** [comment]
Oke, het gaat dus om het werk Holzwege en niet de lemma (die zit ook in onze DB).

Een description krijgen in de work pages is nu wat indirect. Het gaat via de `work_lemma`:

```html
<!-- work_detail.html -->

{% if work_lemma.description %}
<div class="{{ description_prose }} mb-8">
  {{ work_lemma.description | safe }}
</div>
{% endif %}
```

Een `work_lemma` is een lemma (1) waarvan de naam overeenkomt met de title of short-title van een work en (2) die type 'w' heeft. Dat is hoe het ons lukt om de description van _Der Feldweg_ te genereren, op basis van het lemma 'Der Feldweg' dat in onze database zit.

Het probleem hier is dat 'Holzwege' als lemma wel in onze database zit, maar niet type 'w' heeft. Daardoor wordt het als een apart lemma beschouwd – en daar is je description wél terug te vinden: https://heidegger.delve.nu/index/lemma/holzwege.

Nu kan je referentie uit GA 29/30 natuurlijk niet naar het werk _Holzwege_ verwijzen, dus het lijkt me niet wenselijk die lemma het type 'w' te geven. In plaats daarvan is het denk ik een goed idee om een description-veld aan het `Work` model toe te voegen en die op basis van de ID of de slug van de ID toe te voegen (dus `ga-5.md`, zoals je voorstelt, of gewoon `GA 5.md`). Voor de consistentie zou ik dan `Der Feldweg.md` ook hernoemen naar `fw.md` en de `work_lemma.description` in zijn geheel achterwege laten in de work page (dus effectief die vervangen door `work.description`).
