### ISSUE TITLE
Restructure 'related' reftypes

### ISSUE THREAD

**Issue by andredelft** [andredelft/heidegger-index#4]
'Related' should not be a reftype, but rather a relation _between_ lemmata. We should:

- [ ] Clean the data
- [ ] Come up with a new model and wrapper function to generate the DB relations
- [ ] Add links to related lemmata in the lemma detail page

**Comment by johannesdewit** [comment]
Is this really the case? It seems to me that references that use the 'Related' reftype refer to pages that relate to the lemma, but do not mention the lemma explicitely. At least this how I have used it. It is not necessarily the case that there is one term on those pages refering back to the lemma that the reference is assigned to.

It would however be nice to have a way to indicate relationships between two lemmata ofcourse. But I do not think it should replace the option we have now.

Maybe we can call these references that connect to a lemma without explicitely naming it, 'related', which is a property of the reference. And call the lemma's that we want to connect to each other 'analogous' or 'connected' lemma's, which is a property of the lemma's themselves.

**Comment by andredelft** [comment]
The problem I have now with the way I have been using it (which, by the way, I did for only a handfull of lemmata around the beginning of this index) is that I used it to index specific other terms that appeared, but are related to a term which was already present in the index. E.g.: _Grundriß_ I found in ZW (_Die Zeit des Weltbildes_) and I related that to some term I found in EWI, I think it was _Geschick_. This is not the right way to do this, of course. We should have _Grundriß_ and _Geschick_ as different lemmata (_Geschick_ actually does exist now) and have some many-to-many relation in the database, stating that these two terms are 'related'. We can perhaps encode this in the YAML as follows:

```yaml
Grundriß:
  ZW:
  - start: 79
  related:
  - Geschick
```

Or maybe:

```yaml
Grundriß:
  ZW:
  - start: 79
  meta:
    related:
    - Geschick
```

This way we can add similar things under the `meta` field in the future (description, definition, lemma type?).

I do agree with the way you have been using the `r` flag btw, so I think it's good to keep that. But maybe we shouldn't call that 'related', but rather 'implicit' or something?

**Comment by johannesdewit** [comment]
I agree with your distinction and the idea of a `meta` field could work, I think.

Is it the case that the relationship between lemmata is always symmetrical? Or can `a` be related to `b`, without `b` relating to `a`?

'Implicit' could work, at least temporarily. I am not sure whether I like the term very much.

**Comment by johannesdewit** [comment]
Closed because issue is elaborated on and contained in https://github.com/andredelft/heidegger-index/issues/10.
