### ISSUE TITLE
Relating to a non-existing lemma

### ISSUE THREAD

**Issue by johannesdewit** [andredelft/heidegger-index#51]
'[φυσικά](https://github.com/andredelft/heidegger-index/blob/f5761e01da13a4c9ec4557dbc99a205cb603c79a/index/heidegger-index.yml#L6997)' is defined as a related term at the entry 'φύσις', but as 'φυσικά' does not exist as a lemma on its own, the populate script fails.

For now I have removed the related term, but this means a loss of information.

**Comment by andredelft** [comment]
Ik heb φυσικά door φυσικός vervangen omdat het eerste een vervoeging is van het laatste, zie: https://www.perseus.tufts.edu/hopper/morph?l=fusika&la=greek. Die vorm kan dus gewoon toegevoegd worden aan de related terms.
